### ISSUE TITLE
How To Run?

### ISSUE THREAD

**Issue by Several-Geese** [TheNexusAvenger/Enigma#1]
im completely idiot i dont know how code in total, works and i've tried for a hour looking around, litterally. at anything i can regarding the enigma stuff. i just cant do it, maybe im extremely bad at this and cant even tell if it doesnt work, or im not doing it properly. but i cant get it to work myself. been doing this in a public VR supported game for an hour-ish. just trying every random thing i can.. even switched laptops and did it all AGAIN, can a video be released explaining it? does this even work publicly? how much money do i have to give you for you to love me? Im the person with 4 base stations and 7 trackers, but i havent done anything related to code, so im a huge vr person. i want to be able to use this, do a video or something explaining how it works to a toddler if you feel like it, i want this, also never used github until this and made an account just to do this, been yapping for awhile and i think my street-creds low.

**Comment by TheNexusAvenger** [comment]
I think the issue just boils down to "how do I run this".
At the moment, there is no simple release to download and run. Originally, it was planned for tonight, but I am delaying it to tomorrow or very late tonight as I try to resolve an issue.

For whenever it does come out, I'd suggest checking that a server has V.2.11.0-enigma-beta-2 or newer before running the application. V.2.11.0-enigma-beta-1 is out now and has major problems.

**Comment by Several-Geese** [comment]
I love you
20x over thank you

**Comment by TheNexusAvenger** [comment]
The first release is out.
https://github.com/TheNexusAvenger/Enigma/releases/tag/V.0.1.0

For Nexus VR Character Model games, make sure they are running V.2.11.0-enigma-beta-2 or newer (some old servers still have V.2.11.0-enigma-beta-1, and some games use 2.9.0 or earlier). Once the app is running and the Roblox window is focused, open the Nexus VR Character Model menu and go to the second page, and then run the calibrate step.
