### ISSUE TITLE
CFrame is incorrect

### ISSUE THREAD

**Issue by datisniet** [TheNexusAvenger/Enigma#10]
the issue is that this line in roblox outputs 0,0,0,nan,nan,nan,nan,nan,nan,nan,nan,nan
i didnt break the code
self.LastFloorCFrameToOrigin * (CFrame.new(RawInputData.FloorRelativeVelocity * TimeOffset) * RawInputData.FloorRelativeCFrame)

if you need to know what my setup is its a quest 2 with a 3.0 tracker on the front valve controllers and steamvr 2.7.4 and windows 10

**Comment by TheNexusAvenger** [comment]
Something is clearly off with an invalid rotation, but it is unclear what is off. My first guess is whatever software is being used to use SteamVR trackers with the Quest 2. I haven't had issues with my setup, and a way to reproduce this will be required to do anything.

**Comment by datisniet** [comment]
this is the data its sending for one tracker to roblox
2|1|4|0|1|3|1|3|-0,989|-5,647|-20,009|2|4|0,565|-0,454|0,471|0,502|3|3|-0,001|0,003|0,002
is this what you need to help i dont know how it's supposed to look like so i cant work with it but it looks like there is a unneeded 1|3

**Comment by datisniet** [comment]
i found the problem this is the fix

function StringDeserializer.ReadNumber(self: StringDeserializer): number
	local numString = self:ReadString()

	-- Replace comma with period to support the format "0,423"
	numString = string.gsub(numString, ",", ".")

	local num = tonumber(numString)

	if not num then
		error("Failed to convert '" .. numString .. "' to a number.")
	end

	return num
end

the problem is that the exe program gives values like this 0,453 but roblox needs 0.453 one is with , other is with .

**Comment by datisniet** [comment]
thank you for your help.
i got one more question will the v3 version for roblox support waist tracking?

**Comment by TheNexusAvenger** [comment]
Please create separate issues for unrelated questions.
