### ISSUE TITLE
Can't get Vive Tracker 3.0's to work/calibrate

### ISSUE THREAD

**Issue by DevGorthon** [TheNexusAvenger/Enigma#17]
- I'm using two of the Vive Tracker 3.0's
- I have 2 base stations
- The VR I'm using is the Valve Index

When I click `"Calibrate Trackers"` the `"Protocol version: 2"` changes to `"Protocol version: Unsupported"`:

![EnigmaProtocolV2](https://github.com/user-attachments/assets/2c155ab9-c506-479a-a3cb-24174e11ee7f)
![EnigmaUnsupported](https://github.com/user-attachments/assets/2a5a0e17-956d-45cb-b600-abf7fd7de60c)

**I can see the trackers when I click "Show Trackers" and they are labeled as (None) and (None 2):**

![TrackersShown](https://github.com/user-attachments/assets/17f374ed-e668-48f8-bb3a-9840fd294be5)

Result of `enigma-cli.exe list-devices --masked`:
----------------------------------------------------------------------------------------------------------------

[2024-11-28 06:24:45.140] [Info ] Listing OpenVR devices.
[2024-11-28 06:24:45.153] [Info ] OpenVR devices (7):
                                  | [0] /devices/lighthouse/LHR-2######8 (HMD)
                                  |   Properties:
                                  |     Prop_TrackingSystemName_String: "lighthouse"
                                  |     Prop_ModelNumber_String: "Index"
                                  |     Prop_SerialNumber_String: "LHR-2######8"
                                  |     Prop_RenderModelName_String: "generic_hmd"
                                  |     Prop_ManufacturerName_String: "Valve"
                                  |     Prop_TrackingFirmwareVersion_String:
                                  "16###########################################################################00"
                                  |     Prop_HardwareRevision_String: "pr################################# 0"
                                  |     Prop_Firmware_ManualUpdateURL_String:
                                  "https://developer.valvesoftware.com/wiki/SteamVR/HowTo_Update_Firmware"
                                  |     Prop_Firmware_ProgrammingTarget_String: "LHR-2######8"
                                  |     Prop_ResourceRoot_String: "indexhmd"
                                  |     Prop_InputProfilePath_String: "{indexhmd}/input/indexhmd_profile.json"
                                  |     Prop_AdditionalDeviceSettingsPath_String: "{indexhmd}/additional.vrsettings"
                                  |     Prop_ManufacturerSerialNumber_String: "AU########CE"
                                  |     Prop_ComputedSerialNumber_String: "2c############################f0"
                                  |     Prop_CameraFirmwareDescription_String: "Et########################lk"
                                  |     Prop_NamedIconPathControllerLeftDeviceOff_String:
                                  "{indexcontroller}/icons/left_controller_status_off.png"
                                  |     Prop_NamedIconPathControllerRightDeviceOff_String:
                                  "{indexcontroller}/icons/right_controller_status_off.png"
                                  |     Prop_NamedIconPathTrackingReferenceDeviceOff_String:
                                  "{lighthouse}/icons/base2_status_off.png"
                                  |     Prop_ExpectedControllerType_String: "knuckles"
                                  |     Prop_HmdColumnCorrectionSettingPrefix_String: "in########################18"
                                  |     Prop_Audio_DefaultPlaybackDeviceId_String:
                                  "{0###################################################f}"
                                  |     Prop_Audio_DefaultRecordingDeviceId_String:
                                  "{0###################################################b}"
                                  |     Prop_NamedIconPathDeviceOff_String: "{indexhmd}/icons/headset_status_off.png"
                                  |     Prop_NamedIconPathDeviceSearching_String:
                                  "{indexhmd}/icons/headset_status_searching.gif"
                                  |     Prop_NamedIconPathDeviceSearchingAlert_String:
                                  "{indexhmd}/icons/headset_status_searching_alert.gif"
                                  |     Prop_NamedIconPathDeviceReady_String:
                                  "{indexhmd}/icons/headset_status_ready.png"
                                  |     Prop_NamedIconPathDeviceReadyAlert_String:
                                  "{indexhmd}/icons/headset_status_ready_alert.png"
                                  |     Prop_NamedIconPathDeviceNotReady_String:
                                  "{indexhmd}/icons/headset_status_error.png"
                                  |     Prop_NamedIconPathDeviceStandby_String:
                                  "{indexhmd}/icons/headset_status_standby.png"
                                  |     Prop_NamedIconPathDeviceStandbyAlert_String:
                                  "{indexhmd}/icons/headset_status_standby_alert.png"
                                  |     Prop_ControllerType_String: "indexhmd"
                                  | [1] /devices/lighthouse/LHB-C######D (TrackingReference)
                                  |   Properties:
                                  |     Prop_TrackingSystemName_String: "lighthouse"
                                  |     Prop_ModelNumber_String: "Valve SR Imp"
                                  |     Prop_SerialNumber_String: "LHB-C######D"
                                  |     Prop_RenderModelName_String: "lh_basestation_valve_gen2"
                                  |     Prop_ManufacturerName_String: "Valve Corporation"
                                  |     Prop_TrackingFirmwareVersion_String: "####"
                                  |     Prop_HardwareRevision_String: "Va############################################A
                                  "
                                  |     Prop_Firmware_ManualUpdateURL_String:
                                  "https://developer.valvesoftware.com/wiki/SteamVR/HowTo_Update_Firmware"
                                  |     Prop_ResourceRoot_String: "lighthouse"
                                  |     Prop_CompositeFirmwareVersion_String:
                                  "R:####################################################  "
                                  |     Prop_ModeLabel_String: "1"
                                  |     Prop_NamedIconPathDeviceOff_String: "{lighthouse}/icons/base2_status_off.png"
                                  |     Prop_NamedIconPathDeviceSearching_String:
                                  "{lighthouse}/icons/base2_status_searching.gif"
                                  |     Prop_NamedIconPathDeviceSearchingAlert_String:
                                  "{lighthouse}/icons/base2_status_searching_alert.gif"
                                  |     Prop_NamedIconPathDeviceReady_String:
                                  "{lighthouse}/icons/base2_status_ready.png"
                                  |     Prop_NamedIconPathDeviceReadyAlert_String:
                                  "{lighthouse}/icons/base2_status_ready_alert.png"
                                  |     Prop_NamedIconPathDeviceNotReady_String:
                                  "{lighthouse}/icons/base2_status_error.png"
                                  |     Prop_NamedIconPathDeviceStandby_String:
                                  "{lighthouse}/icons/base2_status_standby.png"
                                  |     Prop_NamedIconPathDeviceAlertLow_String:
                                  "{lighthouse}/icons/base_status_ready_low.png"
                                  | [2] /devices/lighthouse/LHB-0######8 (TrackingReference)
                                  |   Properties:
                                  |     Prop_TrackingSystemName_String: "lighthouse"
                                  |     Prop_ModelNumber_String: "Valve SR Imp"
                                  |     Prop_SerialNumber_String: "LHB-0######8"
                                  |     Prop_RenderModelName_String: "lh_basestation_valve_gen2"
                                  |     Prop_ManufacturerName_String: "Valve Corporation"
                                  |     Prop_TrackingFirmwareVersion_String: "####"
                                  |     Prop_HardwareRevision_String: "Va############################################A
                                  "
                                  |     Prop_Firmware_ManualUpdateURL_String:
                                  "https://developer.valvesoftware.com/wiki/SteamVR/HowTo_Update_Firmware"
                                  |     Prop_ResourceRoot_String: "lighthouse"
                                  |     Prop_CompositeFirmwareVersion_String:
                                  "R:####################################################  "
                                  |     Prop_ModeLabel_String: "2"
                                  |     Prop_NamedIconPathDeviceOff_String: "{lighthouse}/icons/base2_status_off.png"
                                  |     Prop_NamedIconPathDeviceSearching_String:
                                  "{lighthouse}/icons/base2_status_searching.gif"
                                  |     Prop_NamedIconPathDeviceSearchingAlert_String:
                                  "{lighthouse}/icons/base2_status_searching_alert.gif"
                                  |     Prop_NamedIconPathDeviceReady_String:
                                  "{lighthouse}/icons/base2_status_ready.png"
                                  |     Prop_NamedIconPathDeviceReadyAlert_String:
                                  "{lighthouse}/icons/base2_status_ready_alert.png"
                                  |     Prop_NamedIconPathDeviceNotReady_String:
                                  "{lighthouse}/icons/base2_status_error.png"
                                  |     Prop_NamedIconPathDeviceStandby_String:
                                  "{lighthouse}/icons/base2_status_standby.png"
                                  |     Prop_NamedIconPathDeviceAlertLow_String:
                                  "{lighthouse}/icons/base_status_ready_low.png"
                                  | [3] /devices/valve/index_controllerLHR-8######B (Controller)
                                  |   Properties:
                                  |     Prop_TrackingSystemName_String: "lighthouse"
                                  |     Prop_ModelNumber_String: "Knuckles Left"
                                  |     Prop_SerialNumber_String: "LHR-8######B"
                                  |     Prop_RenderModelName_String: "{indexcontroller}valve_controller_knu_1_0_left"
                                  |     Prop_ManufacturerName_String: "Valve"
                                  |     Prop_TrackingFirmwareVersion_String:
                                  "16#################################################################################
                                  ##################29"
                                  |     Prop_HardwareRevision_String: "pr################################# 0"
                                  |     Prop_ConnectedWirelessDongle_String: "49##########YM"
                                  |     Prop_Firmware_ManualUpdateURL_String:
                                  "https://developer.valvesoftware.com/wiki/SteamVR/HowTo_Update_Firmware"
                                  |     Prop_Firmware_ProgrammingTarget_String: "LHR-8######B"
                                  |     Prop_ResourceRoot_String: "indexcontroller"
                                  |     Prop_RegisteredDeviceType_String: "valve/index_controllerLHR-8######B"
                                  |     Prop_InputProfilePath_String:
                                  "{indexcontroller}/input/index_controller_profile.json"
                                  |     Prop_ComputedSerialNumber_String: "42############################a8"
                                  |     Prop_NamedIconPathDeviceOff_String:
                                  "{indexcontroller}/icons/left_controller_status_off.png"
                                  |     Prop_NamedIconPathDeviceSearching_String:
                                  "{indexcontroller}/icons/left_controller_status_searching.gif"
                                  |     Prop_NamedIconPathDeviceSearchingAlert_String:
                                  "{indexcontroller}/icons/left_controller_status_searching_alert.gif"
                                  |     Prop_NamedIconPathDeviceReady_String:
                                  "{indexcontroller}/icons/left_controller_status_ready.png"
                                  |     Prop_NamedIconPathDeviceReadyAlert_String:
                                  "{indexcontroller}/icons/left_controller_status_ready_alert.png"
                                  |     Prop_NamedIconPathDeviceNotReady_String:
                                  "{indexcontroller}/icons/left_controller_status_error.png"
                                  |     Prop_NamedIconPathDeviceStandby_String:
                                  "{indexcontroller}/icons/left_controller_status_off.png"
                                  |     Prop_NamedIconPathDeviceAlertLow_String:
                                  "{indexcontroller}/icons/left_controller_status_ready_low.png"
                                  |     Prop_ControllerType_String: "knuckles"
                                  | [4] /devices/htc/vive_trackerLHR-0######1 (GenericTracker)
                                  |   Guessed role: None
                                  |   SteamVR role: None
                                  |   Properties:
                                  |     Prop_TrackingSystemName_String: "lighthouse"
                                  |     Prop_ModelNumber_String: "VIVE Tracker 3.0 MV"
                                  |     Prop_SerialNumber_String: "LHR-0######1"
                                  |     Prop_RenderModelName_String: "{htc}vr_tracker_vive_3_0"
                                  |     Prop_ManufacturerName_String: "HTC"
                                  |     Prop_TrackingFirmwareVersion_String:
                                  "15#################################################################################
                                  ################29"
                                  |     Prop_HardwareRevision_String: "pr################################ 0"
                                  |     Prop_ConnectedWirelessDongle_String: "E5######64"
                                  |     Prop_Firmware_ManualUpdateURL_String:
                                  "https://developer.valvesoftware.com/wiki/SteamVR/HowTo_Update_Firmware"
                                  |     Prop_Firmware_ProgrammingTarget_String: "LHR-0######1"
                                  |     Prop_ResourceRoot_String: "htc"
                                  |     Prop_RegisteredDeviceType_String: "htc/vive_trackerLHR-0######1"
                                  |     Prop_InputProfilePath_String: "{htc}/input/vive_tracker_profile.json"
                                  |     Prop_NamedIconPathDeviceOff_String: "{htc}/icons/tracker_status_off.png"
                                  |     Prop_NamedIconPathDeviceSearching_String:
                                  "{htc}/icons/tracker_status_searching.gif"
                                  |     Prop_NamedIconPathDeviceSearchingAlert_String:
                                  "{htc}/icons/tracker_status_searching_alert.gif"
                                  |     Prop_NamedIconPathDeviceReady_String: "{htc}/icons/tracker_status_ready.png"
                                  |     Prop_NamedIconPathDeviceReadyAlert_String:
                                  "{htc}/icons/tracker_status_ready_alert.png"
                                  |     Prop_NamedIconPathDeviceNotReady_String:
                                  "{htc}/icons/tracker_status_error.png"
                                  |     Prop_NamedIconPathDeviceStandby_String:
                                  "{htc}/icons/tracker_status_standby.png"
                                  |     Prop_NamedIconPathDeviceAlertLow_String:
                                  "{htc}/icons/tracker_status_ready_low.png"
                                  |     Prop_ControllerType_String: "vive_tracker"
                                  | [5] /devices/htc/vive_trackerLHR-0######4 (GenericTracker)
                                  |   Guessed role: None
                                  |   SteamVR role: None
                                  |   Properties:
                                  |     Prop_TrackingSystemName_String: "lighthouse"
                                  |     Prop_ModelNumber_String: "VIVE Tracker 3.0 MV"
                                  |     Prop_SerialNumber_String: "LHR-0######4"
                                  |     Prop_RenderModelName_String: "{htc}vr_tracker_vive_3_0"
                                  |     Prop_ManufacturerName_String: "HTC"
                                  |     Prop_TrackingFirmwareVersion_String:
                                  "15#################################################################################
                                  ################29"
                                  |     Prop_HardwareRevision_String: "pr################################ 0"
                                  |     Prop_ConnectedWirelessDongle_String: "AD######EA"
                                  |     Prop_Firmware_ManualUpdateURL_String:
                                  "https://developer.valvesoftware.com/wiki/SteamVR/HowTo_Update_Firmware"
                                  |     Prop_Firmware_ProgrammingTarget_String: "LHR-0######4"
                                  |     Prop_ResourceRoot_String: "htc"
                                  |     Prop_RegisteredDeviceType_String: "htc/vive_trackerLHR-0######4"
                                  |     Prop_InputProfilePath_String: "{htc}/input/vive_tracker_profile.json"
                                  |     Prop_NamedIconPathDeviceOff_String: "{htc}/icons/tracker_status_off.png"
                                  |     Prop_NamedIconPathDeviceSearching_String:
                                  "{htc}/icons/tracker_status_searching.gif"
                                  |     Prop_NamedIconPathDeviceSearchingAlert_String:
                                  "{htc}/icons/tracker_status_searching_alert.gif"
                                  |     Prop_NamedIconPathDeviceReady_String: "{htc}/icons/tracker_status_ready.png"
                                  |     Prop_NamedIconPathDeviceReadyAlert_String:
                                  "{htc}/icons/tracker_status_ready_alert.png"
                                  |     Prop_NamedIconPathDeviceNotReady_String:
                                  "{htc}/icons/tracker_status_error.png"
                                  |     Prop_NamedIconPathDeviceStandby_String:
                                  "{htc}/icons/tracker_status_standby.png"
                                  |     Prop_NamedIconPathDeviceAlertLow_String:
                                  "{htc}/icons/tracker_status_ready_low.png"
                                  |     Prop_ControllerType_String: "vive_tracker"
                                  | [6] /devices/valve/index_controllerLHR-C######4 (Controller)
                                  |   Properties:
                                  |     Prop_TrackingSystemName_String: "lighthouse"
                                  |     Prop_ModelNumber_String: "Knuckles Right"
                                  |     Prop_SerialNumber_String: "LHR-C######4"
                                  |     Prop_RenderModelName_String: "{indexcontroller}valve_controller_knu_1_0_right"
                                  |     Prop_ManufacturerName_String: "Valve"
                                  |     Prop_TrackingFirmwareVersion_String:
                                  "16#################################################################################
                                  ##################29"
                                  |     Prop_HardwareRevision_String: "pr################################# 0"
                                  |     Prop_ConnectedWirelessDongle_String: "CD##########YB"
                                  |     Prop_Firmware_ManualUpdateURL_String:
                                  "https://developer.valvesoftware.com/wiki/SteamVR/HowTo_Update_Firmware"
                                  |     Prop_Firmware_ProgrammingTarget_String: "LHR-C######4"
                                  |     Prop_ResourceRoot_String: "indexcontroller"
                                  |     Prop_RegisteredDeviceType_String: "valve/index_controllerLHR-C######4"
                                  |     Prop_InputProfilePath_String:
                                  "{indexcontroller}/input/index_controller_profile.json"
                                  |     Prop_ComputedSerialNumber_String: "07############################4a"
                                  |     Prop_NamedIconPathDeviceOff_String:
                                  "{indexcontroller}/icons/right_controller_status_off.png"
                                  |     Prop_NamedIconPathDeviceSearching_String:
                                  "{indexcontroller}/icons/right_controller_status_searching.gif"
                                  |     Prop_NamedIconPathDeviceSearchingAlert_String:
                                  "{indexcontroller}/icons/right_controller_status_searching_alert.gif"
                                  |     Prop_NamedIconPathDeviceReady_String:
                                  "{indexcontroller}/icons/right_controller_status_ready.png"
                                  |     Prop_NamedIconPathDeviceReadyAlert_String:
                                  "{indexcontroller}/icons/right_controller_status_ready_alert.png"
                                  |     Prop_NamedIconPathDeviceNotReady_String:
                                  "{indexcontroller}/icons/right_controller_status_error.png"
                                  |     Prop_NamedIconPathDeviceStandby_String:
                                  "{indexcontroller}/icons/right_controller_status_off.png"
                                  |     Prop_NamedIconPathDeviceAlertLow_String:
                                  "{indexcontroller}/icons/right_controller_status_ready_low.png"
                                  |     Prop_ControllerType_String: "knuckles"
[2024-11-28 06:24:45.153] [Info ] SteamVR tracker roles (7):
                                  | /devices/d4##########_1: LeftFoot
                                  | /devices/d4##########_2: RightFoot
                                  | /devices/d4##########_3: Waist
                                  | /devices/d4##########_4: RightKnee
                                  | /devices/d4##########_5: LeftKnee
                                  | /devices/d4##########_6: RightElbow
                                  | /devices/d4##########_7: LeftElbow

**Comment by noblereign** [comment]
try setting the roles of the trackers in steamvr to left and right foot respectively, this link shows you how you can do it https://rezzil.zendesk.com/hc/en-gb/articles/360013879917-Setting-Tracker-Roles

**Comment by DevGorthon** [comment]
setting the trackers roles to left foot and right foot respectively worked
thanks for the help
