### ISSUE TITLE
Data transfer is not working properly

### ISSUE THREAD

**Issue by Vilmer-niemi** [TheNexusAvenger/Enigma#7]
It says it works the first second but after that it stops saying data transfer is active in Catalog Avatar Creator. I'm using the oculus 2 and steam is installed on another disk.

Enigma:
![image](https://github.com/user-attachments/assets/55330804-7f92-4fb2-b284-2527c3fc3373)

Enigma-cli v5.0:
![image](https://github.com/user-attachments/assets/a3b1bad3-6936-484b-b7f3-4ddda3752f03)

**Comment by TheNexusAvenger** [comment]
Are you keeping the Roblox client focused while running this? It is required for the data transfer to work.

**Comment by Vilmer-niemi** [comment]
> Are you keeping the Roblox client focused while running this? It is required for the data transfer to work.
I am keeping the roblox client focused. I'm not sure why it isn't working.

**Comment by Vilmer-niemi** [comment]
Is there anything I can try?

**Comment by TheNexusAvenger** [comment]
Can you try the `list-devices --masked` command (similar to how you are using either `--debug`)? If there are no devices detected, it won't detect as getting new data.

**Comment by Vilmer-niemi** [comment]
This is what enigma-cli.exe list-devices --masked returns
https://pastebin.com/3C3u6cJ6

**Comment by TheNexusAvenger** [comment]
`list-devices` shows that no additional trackers are being presented to OpenVR/SteamVR. Something is off in your setup that makes it so OpenVR doesn't list any trackers as existing. There isn't anything that Enigma can do to address this.

**Comment by Vilmer-niemi** [comment]
> `list-devices` shows that no additional trackers are being presented to OpenVR/SteamVR. Something is off in your setup that makes it so OpenVR doesn't list any trackers as existing. There isn't anything that Enigma can do to address this.

Shouldn't enigma work without trackers too? I'm not playing with trackers. Enigma doesn't explain a lot what it does, can you clarify what enigma is for?

**Comment by TheNexusAvenger** [comment]
Enigma presents SteamVR tracker information to Roblox. Without hardware trackers of some sort, there is no way for Enigma to know where parts of your body are, so it does nothing. You'll need another tracker provider (either SteamVR like Vive or Tundra, IMU like SlimeVR, or camera-based Amethyst) for Enigma to pick up.

**Comment by Vilmer-niemi** [comment]
Thanks.
