### ISSUE TITLE
doesnt work with Openvr-SpaceCalibrator

### ISSUE THREAD

**Issue by datisniet** [TheNexusAvenger/Enigma#9]
my legs just stright up disappear so please add Openvr-SpaceCalibrator support. even if i have to copy the offset and past it in the program. this is my first time reporting something on github so if i did any thing wrong please for give me. oh and maybe its a good idea to use imgui for a gui. this is my first time reporting something on github so if i did anything wrong please for give me

**Comment by TheNexusAvenger** [comment]
OpenVR Space Calibrator is not something that can be supported. It assigns the transforms (position and rotation) of the trackers transparently to what reads them. I use it for my VR setup and haven't had any issues.

As for ImGui, I'll look into it after RDC.

**Comment by datisniet** [comment]
if your saying that OpenVR Space Calibrator works for you please tell me what you did or what the startup ordor is so i can try it also the version your using please. sorry im not sure if you meant that english is my seccond language

**Comment by TheNexusAvenger** [comment]
I don't have any advice because I am using it "as intended" (Meta Quest 3 with a SteamVR tracker mounted). Please bring up any issues to the GitHub Issues for that project.

**Comment by datisniet** [comment]
do you think the problem has to do with that it spams skipped 60/61/62/63 ticks ever second. it starts spaming as soon as it starts running it is pasting data and mic up says its working but like i said i cant see my legs. i am running win 10 and headset quest 2 with a 3.0 tracker on it on steamvr v2.7.4 . and valve controllers i cant see my trackers in game two. and trying it on mic up
